name: tp_ecommerce
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.3
  riverpod_test: ^2.6.1

  cloud_functions: ^5.0.4
  
  # UI & routing
  cupertino_icons: ^1.0.6
  go_router: ^16.2.1

  # State management
  provider: ^6.1.2
  flutter_riverpod: ^2.6.1

  # Firebase
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0

  # Networking
  dio: ^5.9.0

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4

  # Platform features
  share_plus: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/
  # fonts:
  #   - family: MyFont
  #     fonts:
  #       - asset: fonts/MyFont-Regular.ttf
