name: tp_ecommerce
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'  # adapté à ton SDK/Dart actuel

dependencies:
  flutter:
    sdk: flutter

  # Firebase / Cloud
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_functions: ^6.0.1

  # UI & routing
  cupertino_icons: ^1.0.8
  go_router: ^16.2.1

  # State management
  provider: ^6.1.2
  flutter_riverpod: ^2.6.1

  # Networking
  dio: ^5.9.0

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5

  # Platform features
  share_plus: ^11.1.0

  # Tests
  mocktail: ^1.0.3
  riverpod_test: ^0.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
