// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWCK0YEQJBwjmkAgErC8X0j6mTDCZ8OcI',
    appId: '1:922634780452:web:89114eef63c15e1c1c3db1',
    messagingSenderId: '922634780452',
    projectId: 'shopflutter-mds2025',
    authDomain: 'shopflutter-mds2025.firebaseapp.com',
    storageBucket: 'shopflutter-mds2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv5K7NO6uWe2tKfSc_pLILpj_pFDnw-rE',
    appId: '1:922634780452:android:c6fba86c00618fa91c3db1',
    messagingSenderId: '922634780452',
    projectId: 'shopflutter-mds2025',
    storageBucket: 'shopflutter-mds2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgB5mdGqmI7-pr1ibsVVKkFHqaq21Lcqg',
    appId: '1:922634780452:ios:f9dc8092b0a9b2671c3db1',
    messagingSenderId: '922634780452',
    projectId: 'shopflutter-mds2025',
    storageBucket: 'shopflutter-mds2025.firebasestorage.app',
    iosBundleId: 'com.example.tpEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgB5mdGqmI7-pr1ibsVVKkFHqaq21Lcqg',
    appId: '1:922634780452:ios:f9dc8092b0a9b2671c3db1',
    messagingSenderId: '922634780452',
    projectId: 'shopflutter-mds2025',
    storageBucket: 'shopflutter-mds2025.firebasestorage.app',
    iosBundleId: 'com.example.tpEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWCK0YEQJBwjmkAgErC8X0j6mTDCZ8OcI',
    appId: '1:922634780452:web:c5005e4680369b971c3db1',
    messagingSenderId: '922634780452',
    projectId: 'shopflutter-mds2025',
    authDomain: 'shopflutter-mds2025.firebaseapp.com',
    storageBucket: 'shopflutter-mds2025.firebasestorage.app',
  );
}
