name: Web CD (GitHub Pages)

on:
  push:
    branches: [ main ]
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.2"
          channel: stable
          cache: true

      - name: Pub get
        run: flutter pub get

      - name: Build Web (release)
        run: |
          # Repo Pages => site servi sous /EcommerceFlutter/
          flutter build web --release --pwa-strategy offline-first --base-href "/EcommerceFlutter/"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
